language: r
cache: packages
warnings_are_errors: true
r_check_args: --as-cran --no-manual # Workaround error compiling PDF manual
env:
 - _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    packages:
      - ghostscript

git:
  depth: 1

r_binary_packages:
 - ape
 - covr
 - devtools
 - knitr
 - memoise
 - phangorn
 - R.cache
 - Rcpp
 - Rdpack
 - rmarkdown
 - roxygen2
 - testthat

# Some packages not available as binaries:
r_packages:
 - bookdown
 - CongreveLamsdell2016
 - Ternary
# - TreeTools
 
r_github_packages:
 - ms609/CongreveLamsdell2016
 - ms609/TreeTools
 - ms609/TreeDist

before_script:
  - R -e "pkgload::load_all(); devtools::document()"

matrix:
  include:
    - r: 3.4.0
      addons:
        apt:
          packages: valgrind
      script: R -d "valgrind --leak-check=full --track-origins=yes" --vanilla < tests/testthat.R
    - r: release
      before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
        local_dir: "docs"
        keep-history: true
        on:
          branch: master
    - r: devel
      branches:
        only: master
      after_success:
        - Rscript -e "covr::codecov()"
    - os: osx
      branches:
        only: master
      r: release
      r_packages:
         - ape
         - devtools
         - knitr
         - memoise
         - phangorn
         - R.cache
         - Rcpp
         - Rdpack
         - rmarkdown
         - roxygen2
         - testthat
      before_install:
      - brew install cairo
      - sudo tlmgr install doi titling hyperref framed
